[build]
  publish = "."

[[headers]]
  for = "/public/songs/*.mp3"
  [headers.values]
    Content-Type = "audio/mpeg"
    Accept-Ranges = "bytes"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.mp3"
  [headers.values]
    Content-Type = "audio/mpeg"
    Accept-Ranges = "bytes"
    Cache-Control = "public, max-age=31536000" 